#ifndef PLAYER_SPRITESHEET_H
#define PLAYER_SPRITESHEET_H

#define PLAYER_MAX_COLUMN 10
#define PLAYER_MAX_ROW 10

#define PLAYER_PARTITION_X 16
#define PLAYER_PARTITION_Y 16

// X + Y*PLAYER_MAX_COLUMN
typedef enum {
    PDEATH = 9 + 3*PLAYER_MAX_COLUMN,

    PFRONTIDLE0 = 0 + 0*PLAYER_MAX_COLUMN,
    PFRONTIDLE1 = 1 + 0*PLAYER_MAX_COLUMN,
    PFRONTIDLE2 = 2 + 0*PLAYER_MAX_COLUMN,

    PBACKIDLE0 = 3 + 0*PLAYER_MAX_COLUMN,
    PBACKIDLE1 = 4 + 0*PLAYER_MAX_COLUMN,
    PBACKIDLE2 = 5 + 0*PLAYER_MAX_COLUMN,

    PRIGHTIDLE0 = 6 + 0*PLAYER_MAX_COLUMN,
    PRIGHTIDLE1 = 7 + 0*PLAYER_MAX_COLUMN,

    PLEFTIDLE0 = 8 + 0*PLAYER_MAX_COLUMN,
    PLEFTIDLE1 = 9 + 0*PLAYER_MAX_COLUMN,

    PFRONTWALK0 = 0 + 1*PLAYER_MAX_COLUMN,
    PFRONTWALK1 = 0 + 2*PLAYER_MAX_COLUMN,
    PFRONTWALK2 = 0 + 3*PLAYER_MAX_COLUMN,
    PFRONTWALK_MAX = 3,

    PBACKWALK0 = 3 + 1*PLAYER_MAX_COLUMN,
    PBACKWALK1 = 3 + 2*PLAYER_MAX_COLUMN,
    PBACKWALK2 = 3 + 3*PLAYER_MAX_COLUMN,
    PBACKWALK_MAX = 3,

    PRIGHTWALK0 = 6 + 1*PLAYER_MAX_COLUMN,
    PRIGHTWALK1 = 6 + 2*PLAYER_MAX_COLUMN,
    PRIGHTWALK2 = 6 + 3*PLAYER_MAX_COLUMN,
    PRIGHTWALK_MAX = 3,

    PLEFTWALK0 = 8 + 1*PLAYER_MAX_COLUMN,
    PLEFTWALK1 = 8 + 2*PLAYER_MAX_COLUMN,
    PLEFTWALK2 = 8 + 3*PLAYER_MAX_COLUMN,
    PLEFTWALK_MAX = 3,

    PBLADEBACKRIGHT = 5 + 1*PLAYER_MAX_COLUMN,
    PBLADEBACKLEFT = 5 + 2*PLAYER_MAX_COLUMN,
    PBLADEUPPERRIGHT = 7 + 1*PLAYER_MAX_COLUMN,
    PBLADEUPPERLEFT = 9 + 1*PLAYER_MAX_COLUMN,
    PBLADELOWERRIGHT = 7 + 2*PLAYER_MAX_COLUMN,
    PBLADELOWERLEFT = 9 + 2*PLAYER_MAX_COLUMN,

    PATTACKFRONT = 1 + 1*PLAYER_MAX_COLUMN,
    PATTACKBEHIND = 4 + 1*PLAYER_MAX_COLUMN,
    PATTACKRIGHT = 1 + 3*PLAYER_MAX_COLUMN,
    PATTACKLEFT = 4 + 3*PLAYER_MAX_COLUMN,

    PSTUNFRONT = 9 + 4*PLAYER_MAX_COLUMN,
    PSTUNBACK = 9 + 5*PLAYER_MAX_COLUMN,
    PSTUNRIGHT = 9 + 6*PLAYER_MAX_COLUMN,
    PSTUNLEFT = 9 + 7*PLAYER_MAX_COLUMN,

    PFRONTDASHFACINGFRONT0 = 0 + 4*PLAYER_MAX_COLUMN,
    PFRONTDASHFACINGFRONT1 = 0 + 7*PLAYER_MAX_COLUMN,
    PBACKDASHFACINGFRONT0 = 1 + 4*PLAYER_MAX_COLUMN,
    PBACKDASHFACINGFRONT1 = 1 + 7*PLAYER_MAX_COLUMN,
    PRIGHTDASHFACINGFRONT0 = 1 + 5*PLAYER_MAX_COLUMN,
    PRIGHTDASHFACINGFRONT1 = 0 + 9*PLAYER_MAX_COLUMN,
    PLEFTDASHFACINGFRONT0 = 0 + 5*PLAYER_MAX_COLUMN,
    PLEFTDASHFACINGFRONT1 = 0 + 6*PLAYER_MAX_COLUMN,

    PFRONTDASHFACINGBACK0 = 2 + 4*PLAYER_MAX_COLUMN,
    PFRONTDASHFACINGBACK1 = 2 + 7*PLAYER_MAX_COLUMN,
    PBACKDASHFACINGBACK0 = 3 + 4*PLAYER_MAX_COLUMN,
    PBACKDASHFACINGBACK1 = 3 + 7*PLAYER_MAX_COLUMN,
    PRIGHTDASHFACINGBACK0 = 3 + 5*PLAYER_MAX_COLUMN,
    PRIGHTDASHFACINGBACK1 = 2 + 9*PLAYER_MAX_COLUMN,
    PLEFTDASHFACINGBACK0 = 2 + 5*PLAYER_MAX_COLUMN,
    PLEFTDASHFACINGBACK1 = 2 + 6*PLAYER_MAX_COLUMN,

    PFRONTDASHFACINGRIGHT0 = 4 + 4*PLAYER_MAX_COLUMN,
    PFRONTDASHFACINGRIGHT1 = 4 + 7*PLAYER_MAX_COLUMN,
    PBACKDASHFACINGRIGHT0 = 5 + 4*PLAYER_MAX_COLUMN,
    PBACKDASHFACINGRIGHT1 = 5 + 7*PLAYER_MAX_COLUMN,
    PRIGHTDASHFACINGRIGHT0 = 5 + 5*PLAYER_MAX_COLUMN,
    PRIGHTDASHFACINGRIGHT1 = 4 + 9*PLAYER_MAX_COLUMN,
    PLEFTDASHFACINGRIGHT0 = 4 + 5*PLAYER_MAX_COLUMN,
    PLEFTDASHFACINGRIGHT1 = 4 + 6*PLAYER_MAX_COLUMN,

    PFRONTDASHFACINGLEFT0 = 6 + 4*PLAYER_MAX_COLUMN,
    PFRONTDASHFACINGLEFT1 = 6 + 7*PLAYER_MAX_COLUMN,
    PBACKDASHFACINGLEFT0 = 7 + 4*PLAYER_MAX_COLUMN,
    PBACKDASHFACINGLEFT1 = 7 + 7*PLAYER_MAX_COLUMN,
    PRIGHTDASHFACINGLEFT0 = 7 + 5*PLAYER_MAX_COLUMN,
    PRIGHTDASHFACINGLEFT1 = 6 + 9*PLAYER_MAX_COLUMN,
    PLEFTDASHFACINGLEFT0 = 6 + 5*PLAYER_MAX_COLUMN,
    PLEFTDASHFACINGLEFT1 = 6 + 6*PLAYER_MAX_COLUMN,

    PFIREARROWFRONT = 8 + 4*PLAYER_MAX_COLUMN,
    PFIREARROWBACK = 8 + 5*PLAYER_MAX_COLUMN,
    PFIREARROWRIGHT = 8 + 6*PLAYER_MAX_COLUMN,
    PFIREARROWLEFT = 8 + 7*PLAYER_MAX_COLUMN,

    PPLANTFRONT = 8 + 8*PLAYER_MAX_COLUMN,
    PPLANTBACK = 8 + 9*PLAYER_MAX_COLUMN,
    PPLANTRIGHT = 9 + 8*PLAYER_MAX_COLUMN,
    PPLANTLEFT = 9 + 9*PLAYER_MAX_COLUMN,

} PlayerSpritesheetEnums;

#endif